Repository hackos123/ui_components_stack, pull requests merged in 2024-10, with the labels that each got.

#1 Component Button: added a button
  buttons/777ahesh/index.html
  buttons/777ahesh/style.css
Labels: good first issue, hacktoberfest-accepted

#7 Issue #3 Component Cards
  cards/alexchrysovergis/index.html
  cards/alexchrysovergis/styles.css
Labels: good first issue, hacktoberfest-accepted

#9 Issue #4 Component Input Field
  cards/alexchrysovergis/styles.css
  inputs/alexchrysovergis/index.html
  inputs/alexchrysovergis/styles.css
Labels: enhancement, hacktoberfest-accepted

#11 Add Button Components
  buttons/biswajit-sarkar-007/index.html
  buttons/biswajit-sarkar-007/style.css
Labels: good first issue, hacktoberfest-accepted

#14 Added a card component
  cards/index.html
  cards/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#15 added a card component
  cards/777ahesh/1/index.html
  cards/777ahesh/1/style.css
  cards/777ahesh/2/index.html
  cards/777ahesh/2/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted
